### ISSUE TITLE
Document

### ISSUE THREAD

**Issue by varshini2421** [CederGroupHub/MatBERT-synthesis-classifier#1]
Is there any documentation or paper available for the matbert classifier, something like "Semi-supervised machine-learning classification of materials synthesis procedures" that is available for LDA classifier.

**Comment by hhaoyan** [comment]
Sorry, not for now. But we are working on a paper so make sure to stay tuned!

**Comment by varshini2421** [comment]
Sure, thanks for the contribution, it's very interesting. what is the major advantage or difference between the LDA and matbert, if any?

**Comment by hhaoyan** [comment]
Both LDA and MatBERT are unsupervised (arguably self-supervised) models trained on unlabeled paragraphs and reveal text similarities. They are used as features for the downstream paragraph classification task.

Major advantages of MatBERT:
1. Less prone to numerical instability due to short paragraphs. MatBERT is a better language model that captures long distance information while LDA only assumes bag-of-words. We observed significant performance increase using MatBERT in terms of F1 scores.
2. Faster inference speed because MatBERT can be run with parallelism on GPUs.

Disadvantages are the lack of interpretability of neural networks and the large model size (a few hundred mega bytes).

**Comment by varshini2421** [comment]
Thanks for the information!
